
version: 2.1

orbs:
    codecov: 'codecov/codecov@3.0.0'

.env_common: &env_common
    SHELL: '/bin/bash'

.env_xdebug: &env_xdebug
    XDEBUG_MODE: 'coverage'

.env_composer: &env_composer
    COMPOSER_NO_INTERACTION: '1'
    COMPOSER_MEMORY_LIMIT: '-1'
    COMPOSER_DISABLE_XDEBUG_WARN: '1'
    COMPOSER_CACHE_DIR: '/home/circleci/.cache/composer'

executors:
    php_min:
        environment:
            <<: *env_common
            <<: *env_xdebug
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'circleci/php:7.4'

    php_plus1:
        environment:
            <<: *env_common
            <<: *env_xdebug
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'circleci/php:8.0'

    php_plus2:
        environment:
            <<: *env_common
            <<: *env_xdebug
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'cimg/php:8.1'

commands:
    php_extensions_install:
        description: 'PHP extensions - install'
        steps:
            -
                run:
                    name: 'PHP extensions - install'
                    command: |
                        sudo pecl install pcov

    composer_install:
        description: 'Install Composer dependencies with cache restore and save'
        steps:
            -
                restore_cache:
                    name: 'Composer - cache restore'
                    keys:
                        - 'composer-{{ checksum "./composer.lock" }}-2'

            -
                run:
                    name: 'Composer - install'
                    command: |
                        composer install --no-progress

            -
                save_cache:
                    name: 'Composer - cache save'
                    key: 'composer-{{ checksum "./composer.lock" }}-2'
                    paths:
                        - '~/.cache/composer/'

    lint:
        description: 'Run linters'
        steps:
            -
                run:
                    name: 'Run linters'
                    command: '"./$(composer config bin-dir)/robo" lint'

    test:
        description: 'Run tests'
        steps:
            -
                run:
                    name: 'Codeception - unit'
                    command: |
                        "./$(composer config bin-dir)/robo" test unit
            -
                codecov/upload:
                    flags: 'unit'
                    file: './tests/_log/machine/coverage/unit/coverage.xml'
            -
                store_test_results:
                    name: 'Store unit test results'
                    path: './tests/_log/machine/junit'

jobs:
    build:
        executor: 'php_min'
        working_directory: '~/project'
        steps:
            - 'checkout'
            - 'composer_install'
    lint:
        executor: 'php_min'
        working_directory: '~/project'
        steps:
            - 'checkout'
            - 'composer_install'
            - 'lint'
    test_php_min:
        executor: 'php_min'
        working_directory: '~/project'
        steps:
            - 'checkout'
            - 'php_extensions_install'
            - 'composer_install'
            - 'test'
    test_php_plus1:
        executor: 'php_plus1'
        working_directory: '~/project'
        steps:
            - 'checkout'
            - 'php_extensions_install'
            - 'composer_install'
            - 'test'
    test_php_plus2:
        executor: 'php_plus2'
        working_directory: '~/project'
        steps:
            - 'checkout'
            - 'php_extensions_install'
            - 'composer_install'
            - 'test'

workflows:
    lint_and_test:
        jobs:
            -
                build: {}
            -
                lint:
                    requires:
                        - 'build'
            -
                test_php_min:
                    requires:
                        - 'build'
            -
                test_php_plus1:
                    requires:
                        - 'build'
            -
                test_php_plus2:
                    requires:
                        - 'build'
